src/Blogifier/Controllers/BlogController.cs
using Blogifier.Core;
using Blogifier.Core.Data;
using Blogifier.Core.Helpers;
using Blogifier.Core.Services;
using Blogifier.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace Blogifier.Controllers
{
    public class BlogController : Controller
    {
        protected IDataService DataService;
        protected IStorageService StorageService;
        protected SignInManager<AppUser> SignInManager;
        protected IFeedService FeedService;

        public BlogController(IDataService data, IStorageService storage, SignInManager<AppUser> signInMgr, IFeedService feedService)
        {
            DataService = data;
            StorageService = storage;
            SignInManager = signInMgr;
            FeedService = feedService;
        }

        public async Task<IActionResult> Index(string term, int page = 1)
        {               
            var blog = await DataService.CustomFields.GetBlogSettings();
            var model = new ListModel { 
                Blog = blog, 
                PostListType = PostListType.Blog 
            };
            var pgr = new Pager(page, blog.ItemsPerPage);

            if (string.IsNullOrEmpty(term))
            {
                if(blog.IncludeFeatured)
                    model.Posts = await DataService.BlogPosts.GetList(pgr, 0, "", "FP");
                else
                    model.Posts = await DataService.BlogPosts.GetList(pgr, 0, "", "P");
            }
            else
            {
                model.Posts = await DataService.BlogPosts.Search(pgr, term, 0, "FP");
            }

            if (pgr.ShowOlder) pgr.LinkToOlder = $"blog?page={pgr.Older}";
            if (pgr.ShowNewer) pgr.LinkToNewer = $"blog?page={pgr.Newer}";

            model.Pager = pgr;

            if (!string.IsNullOrEmpty(term))
            {
                model.Blog.Title = term;
                model.Blog.Description = "";
                model.PostListType = PostListType.Search;
            }

            return View($"~/Views/Themes/{blog.Theme}/List.cshtml", model);
        }

        [HttpGet("categories/{name}")]
        public async Task<IActionResult> Categories(string name, int page = 1)
        {
            var blog = await DataService.CustomFields.GetBlogSettings();
            var model = new ListModel
            {
                Blog = blog,
                PostListType = PostListType.Category
            };
            var pgr = new Pager(page, blog.ItemsPerPage);

            model.Posts = await DataService.BlogPosts.GetList(p => p.Categories.Contains(name), pgr);

            if (pgr.ShowOlder) pgr.LinkToOlder = $"?page={pgr.Older}";
            if (pgr.ShowNewer) pgr.LinkToNewer = $"?page={pgr.Newer}";

            model.Pager = pgr;

            return View($"~/Views/Themes/{blog.Theme}/List.cshtml", model);
        }

        [HttpPost]
        public IActionResult Search(string term)
        {
            return Redirect($"/blog?term={term}");
        }

        [HttpGet("posts/{slug}")]
        public async Task<IActionResult> Single(string slug)
        {
            try
            {
                ViewBag.Slug = slug;
                var model = await DataService.BlogPosts.GetModel(slug);

                // If unpublished and unauthorised redirect to error / 404.
                if (model.Post.Published == DateTime.MinValue && !User.Identity.IsAuthenticated)
                {
                    return Redirect("~/error");
                }

                model.Blog = await DataService.CustomFields.GetBlogSettings();
                model.Post.Description = model.Post.Description.MdToHtml();
                model.Post.Content = model.Post.Content.MdToHtml();

                return View($"~/Views/Themes/{model.Blog.Theme}/Post.cshtml", model);
            }
            catch
            {
                return Redirect("~/error");
            }
        }

        [ResponseCache(Duration = 1200)]
        [HttpGet("feed/{type}")]
        public async Task<IActionResult> Rss(string type)
        {
            string host = Request.Scheme + "://" + Request.Host;
            var blog = await DataService.CustomFields.GetBlogSettings();
            var posts = await FeedService.GetEntries(type, host);
            var items = new List<SyndicationItem>();

            var feed = new SyndicationFeed(
                blog.Title, 
                blog.Description, 
                new Uri(host), 
                host, 
                posts.FirstOrDefault().Published
            );

            if (posts != null && posts.Count() > 0)
            {
                foreach (var post in posts)
                {
                    var item = new SyndicationItem(
                        post.Title,
                        post.Description.MdToHtml(),
                        new Uri(post.Id),
                        post.Id,
                        post.Published
                    );
                    item.PublishDate = post.Published;
                    items.Add(item);
                }
            }
            feed.Items = items;

            var settings = new XmlWriterSettings
            {
                Encoding = Encoding.UTF8,
                NewLineHandling = NewLineHandling.Entitize,
                NewLineOnAttributes = true,
                Indent = true
            };

            using (var stream = new MemoryStream())
            {
                using (var xmlWriter = XmlWriter.Create(stream, settings))
                {
                    var rssFormatter = new Rss20FeedFormatter(feed, false);
                    rssFormatter.WriteTo(xmlWriter);
                    xmlWriter.Flush();
                }
                return File(stream.ToArray(), "application/xml; charset=utf-8");
            }
        }

        [HttpPost("upload/{uploadType}")]
        [Authorize]
        public async Task<ActionResult> Upload(IFormFile file, UploadType uploadType, int postId = 0)
        {
            var path = string.Format("{0}/{1}", DateTime.Now.Year, DateTime.Now.Month);
            var asset = await StorageService.UploadFormFile(file, Url.Content("~/"), path);

            if(uploadType == UploadType.AppLogo)
            {
                var logo = DataService.CustomFields.Single(f => f.AuthorId == 0 && f.Name == Constants.BlogLogo);
                if (logo == null)
                    DataService.CustomFields.Add(new CustomField { AuthorId = 0, Name = Constants.BlogLogo, Content = asset.Url });
                else
                    logo.Content = asset.Url;
                DataService.Complete();
            }
            if(uploadType == UploadType.AppCover)
            {
                var cover = DataService.CustomFields.Single(f => f.AuthorId == 0 && f.Name == Constants.BlogCover);
                if (cover == null)
                    DataService.CustomFields.Add(new CustomField { AuthorId = 0, Name = Constants.BlogCover, Content = asset.Url });
                else
                    cover.Content = asset.Url;
                DataService.Complete();
            }
            if(uploadType == UploadType.PostCover)
            {
                await DataService.BlogPosts.SaveCover(postId, asset.Url);
                DataService.Complete();
            }
            if(uploadType == UploadType.Avatar)
            {
                var user = DataService.Authors.Single(a => a.AppUserName == User.Identity.Name);
                user.Avatar = asset.Url;
                DataService.Complete();
            }

            return Json(new { asset.Url });
        }

        [HttpPost]
        public IActionResult Subscribe(string email)
        {
            if (!string.IsNullOrEmpty(email) && email.IsEmail())
            {
                try
                {
                    var existing = DataService.Newsletters.Single(n => n.Email == email);
                    if (existing == null)
                    {
                        DataService.Newsletters.Add(new Newsletter { Email = email });
                        DataService.Complete();
                    }
                }
                catch (Exception ex)
                {
                    return Ok(ex.Message);
                }
            }
            return Ok();
        }

        [HttpGet("account/logout")]
        public async Task<IActionResult> Logout()
        {
            await SignInManager.SignOutAsync();
            return Redirect("~/blog");
        }
    }
}

src/Blogifier/Views/Themes/Standard/Shared/Footer.cshtml
@using Askmethat.Aspnet.JsonLocalizer.Localizer
@inject IJsonStringLocalizer<ListModel> Localizer
<div class="modal fade blog-search" id="blog-search" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body p-0">
                <form role="search" asp-controller="Blog" asp-action="Search" method="post">
                    <input type="search" id="term" name="term" class="form-control form-control-lg" placeholder="@Localizer["search"]" autocomplete="off">
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container" id="newsletter">
    <div class="jumbotron" id="newsletter-form">
        <h2 class="newsletter-title" id="ttlNewsletter" style="display:none">@Localizer["thank-you"]</h2>
        <form id="frmNewsletter">
            <div class="form-group">
                <h2 class="newsletter-title">@Localizer["newsletter"]</h2>
                <div class="form-group">
                    <input class="form-control" id="txtEmail" name="txtEmail" placeholder="@Localizer["enter-email"]" type="text">
                </div>
                <small class="form-text text-muted" id="emailHelp">
                    @Localizer["join-subscribers"]
                </small>
            </div>
            <button id="blog-subscribe" class="btn btn-subscribe btn-rounded btn-dark">@Localizer["subscribe"]</button>
        </form>
    </div>
</div>

<footer class="blog-footer">
    <div class="container d-lg-flex text-center text-lg-left">
        <p>Copyright © @DateTime.Now.Year. Powered by <a href="https://github.com/blogifierdotnet/Blogifier" data-toggle="tooltip" target="_blank" title="Version - @AppSettings.Version">Blogifier</a>. Designed by <a href="https://francis.bio/" target="_blank" rel="nofollow">Francis</a>.</p>
        <div class="ml-auto">
            @if (User.Identity.IsAuthenticated)
            {
                <a href="~/admin">@Localizer["admin"]</a>
            }
            else
            {
                <a href="~/account/login">@Localizer["login"]</a>
            }
        </div>
    </div>
</footer>

<environment include="Development">
    <script src="~/themes/standard/js/jquery.min.js"></script>
    <script src="~/themes/standard/js/popper.min.js"></script>
    <script src="~/themes/standard/js/bootstrap.min.js"></script>
    <script src="~/themes/standard/js/prism.js"></script>
    <script src="~/themes/standard/js/blog.js" asp-append-version="true"></script>
    <script src="~/admin/js/newsletter.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="~/themes/standard/js/standard.min.js"></script>
</environment>

<partial name="~/Views/Shared/FooterScript.cshtml" />

src/Blogifier/Views/Themes/Standard/Shared/Head.cshtml
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700|Merriweather:700" rel="stylesheet">
<environment include="Development">
    <link href="~/themes/standard/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/themes/standard/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/themes/standard/css/prism.css" rel="stylesheet">
    <link href="~/themes/standard/css/styles.min.css" rel="stylesheet" asp-append-version="true">
</environment>
<environment exclude="Development">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="~/themes/standard/css/standard.min.css" rel="stylesheet">
</environment>
    <link rel="shortcut icon" href="~/themes/standard/img/standard.ico">
<partial name="~/Views/Shared/HeaderScript.cshtml" />

src/Blogifier/Views/Themes/Standard/Shared/Header.cshtml
<header class="blog-header d-flex flex-column">
    <div class="container d-flex">
        <a href="~/blog" class="blog-logo my-auto d-flex">
            <img src="~/themes/standard/img/logo-white.png" alt="Blog Title" class="my-auto" />
        </a>
        <ul class="blog-social nav ml-auto my-auto">
            @foreach (var field in Model)
            {
                <li class="blog-social-item">
                    <a class="blog-social-link" target="_blank" href="@field.Content">
                        <i class="blog-social-icon fa @field.Icon"></i>
                    </a>
                </li>
            }
            <li class="blog-social-item">
                <a class="blog-social-link" target="_blank" href="feed/rss">
                    <i class="blog-social-icon fa fa-rss"></i>
                </a>
            </li>
        </ul>
        <button class="blog-search-toggle btn-unstyled" type="button" data-toggle="modal" data-target="#blog-search">
            <i class="fa fa-search"></i>
        </button>
        <ul class="blog-social nav my-auto nav-login">
            <li class="blog-social-item">
                <a class="blog-social-link" href="~/admin">
                    <i class="fa fa-user" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</header>
@{
    AppSettings.SiteRoot = Url.Content("~/");
}